// Code generated by Icestudio 0.10-rc1

`default_nettype none

//---- Top entity
module main #(
 parameter v2114be = 1,
 parameter v56130b = 1,
 parameter v4bafd0 = 2,
 parameter v4bfbee = 2,
 parameter vb97fc2 = 0,
 parameter v6725bc = 0,
 parameter v8d117e = 1,
 parameter vf32f30 = 1,
 parameter v57e811 = "v57e811.list",
 parameter v4ca317 = "v4ca317.list",
 parameter v89da20 = 240000-1
) (
 input vf5eb20,
 input vb5a0bc,
 input vd59c6a,
 input vfa88c0,
 input vclk,
 output v4adeba,
 output v67f4f7,
 output vab6266,
 output va736c9,
 output [3:0] v88719b,
 output [0:1] vinit
);
 localparam p0 = v89da20;
 localparam p10 = v57e811;
 localparam p11 = v4ca317;
 localparam p12 = v4bafd0;
 localparam p13 = vb97fc2;
 localparam p14 = v8d117e;
 localparam p15 = v4bfbee;
 localparam p16 = v6725bc;
 localparam p17 = vf32f30;
 localparam p25 = v2114be;
 localparam p26 = v56130b;
 localparam p28 = v2114be;
 localparam p29 = v56130b;
 localparam p31 = v2114be;
 localparam p32 = v56130b;
 localparam p34 = v2114be;
 localparam p35 = v56130b;
 wire [0:19] w1;
 wire w2;
 wire w3;
 wire [0:19] w4;
 wire w5;
 wire w6;
 wire [0:19] w7;
 wire [0:19] w8;
 wire [0:19] w9;
 wire w18;
 wire w19;
 wire [0:1] w20;
 wire w21;
 wire w22;
 wire [0:1] w23;
 wire w24;
 wire w27;
 wire w30;
 wire w33;
 wire [0:3] w36;
 wire w37;
 wire w38;
 wire w39;
 wire w40;
 wire w41;
 wire w42;
 wire w43;
 wire [0:3] w44;
 wire [0:3] w45;
 wire w46;
 wire w47;
 wire w48;
 wire w49;
 assign v4adeba = w2;
 assign v67f4f7 = w3;
 assign vab6266 = w5;
 assign va736c9 = w6;
 assign w24 = vf5eb20;
 assign w27 = vb5a0bc;
 assign w30 = vd59c6a;
 assign w33 = vfa88c0;
 assign v88719b = w36;
 assign w37 = vclk;
 assign w38 = vclk;
 assign w39 = vclk;
 assign w40 = vclk;
 assign w41 = vclk;
 assign w42 = vclk;
 assign w43 = vclk;
 assign w3 = w2;
 assign w6 = w5;
 assign w7 = w4;
 assign w38 = w37;
 assign w39 = w37;
 assign w39 = w38;
 assign w40 = w37;
 assign w40 = w38;
 assign w40 = w39;
 assign w41 = w37;
 assign w41 = w38;
 assign w41 = w39;
 assign w41 = w40;
 assign w42 = w37;
 assign w42 = w38;
 assign w42 = w39;
 assign w42 = w40;
 assign w42 = w41;
 assign w43 = w37;
 assign w43 = w38;
 assign w43 = w39;
 assign w43 = w40;
 assign w43 = w41;
 assign w43 = w42;
 assign w44 = w36;
 assign w45 = w36;
 assign w45 = w44;
 v95d0ae #(
  .vc5c8ea(p0)
 ) v93cc1c (
  .v2531bd(w1)
 );
 v82aaa0 v0b7853 (
  .vb2cfec(w1),
  .vb319d4(w4),
  .v6dda25(w37)
 );
 v1bc657 v610f98 (
  .v4642b6(w2),
  .v0e4f6c(w4),
  .v0a4fd8(w8)
 );
 v1bc657 vbd0afc (
  .v4642b6(w5),
  .v0e4f6c(w7),
  .v0a4fd8(w9)
 );
 ve2cdb0 #(
  .vb36a78(p10)
 ) v65d18b (
  .vfde47f(w8),
  .v851180(w44)
 );
 ve2cdb0 #(
  .vb36a78(p11)
 ) v73d4e9 (
  .vfde47f(w9),
  .v851180(w45)
 );
 va8938c #(
  .v7245c7(p12),
  .vd63c4a(p13),
  .v4365a5(p14)
 ) v743732 (
  .v585e5b(w20),
  .v64da9b(w38),
  .v27dec4(w46),
  .v7e359d(w47)
 );
 va8938c #(
  .v7245c7(p15),
  .vd63c4a(p16),
  .v4365a5(p17)
 ) vdb4622 (
  .v585e5b(w23),
  .v64da9b(w39),
  .v7e359d(w48),
  .v27dec4(w49)
 );
 v84f0a1 vd747a1 (
  .vd84a57(w18),
  .vf8041d(w19),
  .vee8a83(w21),
  .v03aaf0(w22),
  .v11bca5(w36)
 );
 v0dbcb9 v241234 (
  .v3f8943(w18),
  .v64d863(w19),
  .v8b19dd(w20)
 );
 v0dbcb9 v70900d (
  .v3f8943(w21),
  .v64d863(w22),
  .v8b19dd(w23)
 );
 v888484 #(
  .v9d2d5b(p25),
  .v42e61f(p26)
 ) vf812ff (
  .vd9601b(w24),
  .vfde3d7(w40),
  .v64879c(w48)
 );
 v888484 #(
  .v9d2d5b(p28),
  .v42e61f(p29)
 ) v09fc70 (
  .vd9601b(w27),
  .vfde3d7(w41),
  .v64879c(w49)
 );
 v888484 #(
  .v9d2d5b(p31),
  .v42e61f(p32)
 ) vdde0e5 (
  .vd9601b(w30),
  .vfde3d7(w42),
  .v64879c(w46)
 );
 v888484 #(
  .v9d2d5b(p34),
  .v42e61f(p35)
 ) v61e9ab (
  .vd9601b(w33),
  .vfde3d7(w43),
  .v64879c(w47)
 );
 assign vinit = 2'b00;
endmodule

//---- Top entity
module v95d0ae #(
 parameter vc5c8ea = 0
) (
 output [19:0] v2531bd
);
 localparam p0 = vc5c8ea;
 wire [0:19] w1;
 assign v2531bd = w1;
 v95d0ae_v465065 #(
  .VALUE(p0)
 ) v465065 (
  .k(w1)
 );
endmodule

//---------------------------------------------------
//-- 20-bits-gen-constant
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Generic: 20-bits generic constant
//---------------------------------------------------

module v95d0ae_v465065 #(
 parameter VALUE = 0
) (
 output [19:0] k
);
 assign k = VALUE;
endmodule
//---- Top entity
module v82aaa0 (
 input v6dda25,
 input [19:0] vb2cfec,
 output [19:0] vb319d4,
 output ve37344
);
 wire [0:19] w0;
 wire w1;
 wire [0:19] w2;
 wire [0:19] w3;
 wire w4;
 wire w5;
 assign w1 = v6dda25;
 assign vb319d4 = w2;
 assign w3 = vb2cfec;
 assign ve37344 = w4;
 assign w2 = w0;
 assign w5 = w4;
 v2d3c65 v55c934 (
  .v545b15(w0),
  .v6dda25(w1),
  .ve556f1(w5)
 );
 vb9ddd5 v90643f (
  .v07eb94(w0),
  .vdb40a4(w3),
  .v4642b6(w4)
 );
endmodule

//---------------------------------------------------
//-- syscounter-M-20bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- syscounter-M-20-bits: 2-bits Module M Syscounter
//---------------------------------------------------
//---- Top entity
module v2d3c65 (
 input v6dda25,
 input ve556f1,
 output [19:0] v545b15,
 output ve37344
);
 wire w0;
 wire [0:19] w1;
 wire [0:19] w2;
 wire w3;
 wire [0:19] w4;
 wire w5;
 assign w0 = ve556f1;
 assign w3 = v6dda25;
 assign v545b15 = w4;
 assign ve37344 = w5;
 assign w4 = w1;
 v8c6884 vfba29e (
  .v782748(w0),
  .v1be022(w1),
  .vf06540(w2),
  .v6dda25(w3)
 );
 vd98b4e v91c0a7 (
  .v4ad898(w1),
  .vd1d627(w2),
  .v4642b6(w5)
 );
endmodule

//---------------------------------------------------
//-- syscounter-rst-16bits CLONE
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 16-bits Syscounter with reset
//---------------------------------------------------
//---- Top entity
module v8c6884 (
 input v6dda25,
 input v782748,
 input [19:0] vf06540,
 output [19:0] v1be022
);
 wire [0:19] w0;
 wire [0:15] w1;
 wire [0:3] w2;
 wire [0:19] w3;
 wire [0:3] w4;
 wire [0:15] w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 assign w0 = vf06540;
 assign v1be022 = w3;
 assign w6 = v6dda25;
 assign w7 = v6dda25;
 assign w8 = v782748;
 assign w9 = v782748;
 assign w7 = w6;
 assign w9 = w8;
 v5c75f6 v9f7443 (
  .v4de61b(w2),
  .v50034e(w4),
  .v6dda25(w6),
  .v782748(w8)
 );
 vafdfd8 vae4b72 (
  .v0bc190(w0),
  .vb68a0b(w1),
  .vd8e8a3(w2)
 );
 vbc711b v5796e0 (
  .vc320da(w1),
  .v3f90b8(w5),
  .v6dda25(w7),
  .v782748(w9)
 );
 vdecca3 v0ddafc (
  .v2e2bd0(w3),
  .v55cd06(w4),
  .vbf8961(w5)
 );
endmodule

//---------------------------------------------------
//-- DFF-rst-x20
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- DFF-rst-x20: 20 D flip-flops in paralell with reset
//---------------------------------------------------
//---- Top entity
module v5c75f6 (
 input v6dda25,
 input v782748,
 input [3:0] v4de61b,
 output [3:0] v50034e
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire [0:3] w6;
 wire [0:3] w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 assign w6 = v4de61b;
 assign v50034e = w7;
 assign w10 = v6dda25;
 assign w11 = v6dda25;
 assign w12 = v6dda25;
 assign w13 = v6dda25;
 assign w14 = v782748;
 assign w15 = v782748;
 assign w16 = v782748;
 assign w17 = v782748;
 assign w11 = w10;
 assign w12 = w10;
 assign w12 = w11;
 assign w13 = w10;
 assign w13 = w11;
 assign w13 = w12;
 assign w15 = w14;
 assign w16 = w14;
 assign w16 = w15;
 assign w17 = w14;
 assign w17 = w15;
 assign w17 = w16;
 vc4f23a v4b1225 (
  .v3f8943(w2),
  .v64d863(w3),
  .vda577d(w4),
  .v985fcb(w6),
  .v4f1fd3(w8)
 );
 v84f0a1 v6491fd (
  .v03aaf0(w0),
  .vee8a83(w1),
  .vf8041d(w5),
  .v11bca5(w7),
  .vd84a57(w9)
 );
 v2be0f8 v10a04f (
  .v4642b6(w0),
  .vf354ee(w3),
  .vd53b77(w13),
  .v27dec4(w17)
 );
 v2be0f8 v7d9648 (
  .v4642b6(w1),
  .vf354ee(w2),
  .vd53b77(w12),
  .v27dec4(w16)
 );
 v2be0f8 v004b14 (
  .vf354ee(w4),
  .v4642b6(w5),
  .vd53b77(w11),
  .v27dec4(w15)
 );
 v2be0f8 v8aa818 (
  .vf354ee(w8),
  .v4642b6(w9),
  .vd53b77(w10),
  .v27dec4(w14)
 );
endmodule

//---------------------------------------------------
//-- DFF-rst-x04
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- DFF-rst-x04: Three D flip-flops in paralell with reset
//---------------------------------------------------
//---- Top entity
module vc4f23a (
 input [3:0] v985fcb,
 output v4f1fd3,
 output vda577d,
 output v3f8943,
 output v64d863
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire [0:3] w4;
 assign v3f8943 = w0;
 assign v64d863 = w1;
 assign vda577d = w2;
 assign v4f1fd3 = w3;
 assign w4 = v985fcb;
 vc4f23a_v9a2a06 v9a2a06 (
  .o1(w0),
  .o0(w1),
  .o2(w2),
  .o3(w3),
  .i(w4)
 );
endmodule

//---------------------------------------------------
//-- Bus4-Split-all
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus4-Split-all: Split the 4-bits bus into its wires
//---------------------------------------------------

module vc4f23a_v9a2a06 (
 input [3:0] i,
 output o3,
 output o2,
 output o1,
 output o0
);
 assign o3 = i[3];
 assign o2 = i[2];
 assign o1 = i[1];
 assign o0 = i[0];
endmodule
//---- Top entity
module v84f0a1 (
 input vd84a57,
 input vf8041d,
 input vee8a83,
 input v03aaf0,
 output [3:0] v11bca5
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire [0:3] w4;
 assign w0 = vee8a83;
 assign w1 = v03aaf0;
 assign w2 = vf8041d;
 assign w3 = vd84a57;
 assign v11bca5 = w4;
 v84f0a1_v9a2a06 v9a2a06 (
  .i1(w0),
  .i0(w1),
  .i2(w2),
  .i3(w3),
  .o(w4)
 );
endmodule

//---------------------------------------------------
//-- Bus4-Join-all
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus4-Join-all: Join all the wires into a 4-bits Bus
//---------------------------------------------------

module v84f0a1_v9a2a06 (
 input i3,
 input i2,
 input i1,
 input i0,
 output [3:0] o
);
 assign o = {i3, i2, i1, i0};
 
endmodule
//---- Top entity
module v2be0f8 #(
 parameter vbd3217 = 0
) (
 input vd53b77,
 input v27dec4,
 input vf354ee,
 output v4642b6
);
 localparam p5 = vbd3217;
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w6;
 assign w2 = v27dec4;
 assign w3 = vf354ee;
 assign v4642b6 = w4;
 assign w6 = vd53b77;
 v3676a0 v7539bf (
  .vcbab45(w1),
  .v0e28cb(w2)
 );
 vba518e vfe8158 (
  .vcbab45(w0),
  .v0e28cb(w1),
  .v3ca442(w3)
 );
 v053dc2 #(
  .v71e305(p5)
 ) vd104a4 (
  .vf54559(w0),
  .ve8318d(w4),
  .va4102a(w6)
 );
endmodule

//---------------------------------------------------
//-- DFF-rst-x01
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- DFF-rst-x01: D Flip flop with reset input. When rst=1, the DFF is 0
//---------------------------------------------------
//---- Top entity
module v3676a0 (
 input v0e28cb,
 output vcbab45
);
 wire w0;
 wire w1;
 assign w0 = v0e28cb;
 assign vcbab45 = w1;
 v3676a0_vd54ca1 vd54ca1 (
  .a(w0),
  .q(w1)
 );
endmodule

//---------------------------------------------------
//-- NOT
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- NOT gate (Verilog implementation)
//---------------------------------------------------

module v3676a0_vd54ca1 (
 input a,
 output q
);
 //-- NOT Gate
 assign q = ~a;
 
 
endmodule
//---- Top entity
module vba518e (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 vba518e_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- AND2
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Two bits input And gate
//---------------------------------------------------

module vba518e_vf4938a (
 input a,
 input b,
 output c
);
 //-- AND gate
 //-- Verilog implementation
 
 assign c = a & b;
 
endmodule
//---- Top entity
module v053dc2 #(
 parameter v71e305 = 0
) (
 input va4102a,
 input vf54559,
 output ve8318d
);
 localparam p2 = v71e305;
 wire w0;
 wire w1;
 wire w3;
 assign w0 = va4102a;
 assign ve8318d = w1;
 assign w3 = vf54559;
 v053dc2_vb8adf8 #(
  .INI(p2)
 ) vb8adf8 (
  .clk(w0),
  .q(w1),
  .d(w3)
 );
endmodule

//---------------------------------------------------
//-- DFF
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- D Flip-flop (verilog implementation)
//---------------------------------------------------

module v053dc2_vb8adf8 #(
 parameter INI = 0
) (
 input clk,
 input d,
 output q
);
 //-- Initial value
 reg q = INI;
 
 //-- Capture the input data  
 //-- on the rising edge of  
 //-- the system clock
 always @(posedge clk)
   q <= d;
endmodule
//---- Top entity
module vafdfd8 (
 input [19:0] v0bc190,
 output [3:0] vd8e8a3,
 output [15:0] vb68a0b
);
 wire [0:15] w0;
 wire [0:3] w1;
 wire [0:19] w2;
 assign vb68a0b = w0;
 assign vd8e8a3 = w1;
 assign w2 = v0bc190;
 vafdfd8_v9a2a06 v9a2a06 (
  .o0(w0),
  .o1(w1),
  .i(w2)
 );
endmodule

//---------------------------------------------------
//-- Bus20-Split-4-16
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus20-Split-4-16: Split the 20-bits bus into two buses of 4 and 16 wires
//---------------------------------------------------

module vafdfd8_v9a2a06 (
 input [19:0] i,
 output [3:0] o1,
 output [15:0] o0
);
 assign o1 = i[19:16];
 assign o0 = i[15:0];
endmodule
//---- Top entity
module vbc711b (
 input v6dda25,
 input v782748,
 input [15:0] vc320da,
 output [15:0] v3f90b8
);
 wire [0:15] w0;
 wire [0:15] w1;
 wire [0:3] w2;
 wire [0:3] w3;
 wire [0:3] w4;
 wire [0:3] w5;
 wire [0:3] w6;
 wire [0:3] w7;
 wire [0:3] w8;
 wire [0:3] w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 assign w0 = vc320da;
 assign v3f90b8 = w1;
 assign w10 = v6dda25;
 assign w11 = v6dda25;
 assign w12 = v6dda25;
 assign w13 = v6dda25;
 assign w14 = v782748;
 assign w15 = v782748;
 assign w16 = v782748;
 assign w17 = v782748;
 assign w11 = w10;
 assign w12 = w10;
 assign w12 = w11;
 assign w13 = w10;
 assign w13 = w11;
 assign w13 = w12;
 assign w15 = w14;
 assign w16 = w14;
 assign w16 = w15;
 assign w17 = w14;
 assign w17 = w15;
 assign w17 = w16;
 v5c75f6 vbdef88 (
  .v4de61b(w2),
  .v50034e(w6),
  .v6dda25(w13),
  .v782748(w17)
 );
 v5c75f6 v6188f9 (
  .v4de61b(w3),
  .v50034e(w7),
  .v6dda25(w12),
  .v782748(w16)
 );
 v852bc8 vd47660 (
  .v91b9c1(w0),
  .v527ffb(w2),
  .v71a717(w3),
  .v0b337e(w4),
  .vfc89f9(w5)
 );
 v401a28 v3ef916 (
  .v14a530(w1),
  .vcc76e8(w6),
  .vd531e6(w7),
  .v7ef7d6(w8),
  .v1447f2(w9)
 );
 v5c75f6 v9f7443 (
  .v4de61b(w4),
  .v50034e(w8),
  .v6dda25(w11),
  .v782748(w15)
 );
 v5c75f6 vd2d6b6 (
  .v4de61b(w5),
  .v50034e(w9),
  .v6dda25(w10),
  .v782748(w14)
 );
endmodule

//---------------------------------------------------
//-- DFF-rst-x16
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- DFF-rst-x16: 16 D flip-flops in paralell with reset
//---------------------------------------------------
//---- Top entity
module v852bc8 (
 input [15:0] v91b9c1,
 output [3:0] vfc89f9,
 output [3:0] v0b337e,
 output [3:0] v71a717,
 output [3:0] v527ffb
);
 wire [0:15] w0;
 wire [0:3] w1;
 wire [0:3] w2;
 wire [0:3] w3;
 wire [0:3] w4;
 assign w0 = v91b9c1;
 assign v527ffb = w1;
 assign v71a717 = w2;
 assign v0b337e = w3;
 assign vfc89f9 = w4;
 v852bc8_v9a2a06 v9a2a06 (
  .i(w0),
  .o0(w1),
  .o1(w2),
  .o2(w3),
  .o3(w4)
 );
endmodule

//---------------------------------------------------
//-- Bus16-Split-quarter
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus16-Split-quarter: Split the 16-bits bus into four buses of the same size
//---------------------------------------------------

module v852bc8_v9a2a06 (
 input [15:0] i,
 output [3:0] o3,
 output [3:0] o2,
 output [3:0] o1,
 output [3:0] o0
);
 assign o3 = i[15:12];
 assign o2 = i[11:8];
 assign o1 = i[7:4];
 assign o0 = i[3:0];
endmodule
//---- Top entity
module v401a28 (
 input [3:0] v1447f2,
 input [3:0] v7ef7d6,
 input [3:0] vd531e6,
 input [3:0] vcc76e8,
 output [15:0] v14a530
);
 wire [0:15] w0;
 wire [0:3] w1;
 wire [0:3] w2;
 wire [0:3] w3;
 wire [0:3] w4;
 assign v14a530 = w0;
 assign w1 = vcc76e8;
 assign w2 = vd531e6;
 assign w3 = v7ef7d6;
 assign w4 = v1447f2;
 v401a28_v9a2a06 v9a2a06 (
  .o(w0),
  .i0(w1),
  .i1(w2),
  .i2(w3),
  .i3(w4)
 );
endmodule

//---------------------------------------------------
//-- Bus16-Join-quarter
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus16-Join-quarter: Join the four same buses into an 16-bits Bus
//---------------------------------------------------

module v401a28_v9a2a06 (
 input [3:0] i3,
 input [3:0] i2,
 input [3:0] i1,
 input [3:0] i0,
 output [15:0] o
);
 assign o = {i3, i2, i1, i0};
 
endmodule
//---- Top entity
module vdecca3 (
 input [3:0] v55cd06,
 input [15:0] vbf8961,
 output [19:0] v2e2bd0
);
 wire [0:19] w0;
 wire [0:15] w1;
 wire [0:3] w2;
 assign v2e2bd0 = w0;
 assign w1 = vbf8961;
 assign w2 = v55cd06;
 vdecca3_v9a2a06 v9a2a06 (
  .o(w0),
  .i0(w1),
  .i1(w2)
 );
endmodule

//---------------------------------------------------
//-- Bus20-Join-4-16
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus20-Join-half: Join the two buses into an 20-bits Bus
//---------------------------------------------------

module vdecca3_v9a2a06 (
 input [3:0] i1,
 input [15:0] i0,
 output [19:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module vd98b4e #(
 parameter v6c5139 = 1
) (
 input [19:0] v4ad898,
 output v4642b6,
 output [19:0] vd1d627
);
 localparam p1 = v6c5139;
 wire w0;
 wire [0:19] w2;
 wire [0:19] w3;
 assign v4642b6 = w0;
 assign w2 = v4ad898;
 assign vd1d627 = w3;
 vf09b6a #(
  .vd73390(p1)
 ) v13dd2b (
  .v4642b6(w0),
  .vf0a425(w2),
  .va63e91(w3)
 );
endmodule

//---------------------------------------------------
//-- Inc1-20bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Inc1-20bit: Increment a 20-bits number by one
//---------------------------------------------------
//---- Top entity
module vf09b6a #(
 parameter vd73390 = 0
) (
 input [19:0] vf0a425,
 output v4642b6,
 output [19:0] va63e91
);
 localparam p1 = vd73390;
 wire w0;
 wire [0:19] w2;
 wire [0:19] w3;
 wire [0:19] w4;
 assign v4642b6 = w0;
 assign w3 = vf0a425;
 assign va63e91 = w4;
 v4e3dc9 vb19a98 (
  .v4642b6(w0),
  .ve4715b(w2),
  .v4895ee(w3),
  .vd66696(w4)
 );
 v95d0ae #(
  .vc5c8ea(p1)
 ) v1ff9a2 (
  .v2531bd(w2)
 );
endmodule

//---------------------------------------------------
//-- AdderK-16bits CLONE
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- AdderK-16bit: Adder of 16-bit operand and 16-bit constant
//---------------------------------------------------
//---- Top entity
module v4e3dc9 (
 input [19:0] ve4715b,
 input [19:0] v4895ee,
 output v4642b6,
 output [19:0] vd66696
);
 wire w0;
 wire [0:7] w1;
 wire [0:7] w2;
 wire [0:11] w3;
 wire [0:19] w4;
 wire [0:19] w5;
 wire [0:11] w6;
 wire w7;
 wire w8;
 wire [0:3] w9;
 wire [0:15] w10;
 wire [0:19] w11;
 wire [0:3] w12;
 wire [0:3] w13;
 wire [0:7] w14;
 wire [0:7] w15;
 wire [0:7] w16;
 wire [0:7] w17;
 assign w4 = v4895ee;
 assign w5 = ve4715b;
 assign v4642b6 = w8;
 assign vd66696 = w11;
 vcb23aa v8e0bba (
  .v4642b6(w0),
  .v62bf25(w2),
  .v39966a(w16),
  .veb2f59(w17)
 );
 vc3c498 v917bbf (
  .vb9cfc3(w0),
  .veeaa8e(w1),
  .v4642b6(w7),
  .v45c6ee(w14),
  .v20212e(w15)
 );
 v8cc49c v03c3e3 (
  .vb334ae(w1),
  .v2b8a97(w2),
  .v14a530(w10)
 );
 v0f6c39 v672b5a (
  .vb09d88(w3),
  .v0bc190(w4),
  .ve1a6e8(w17)
 );
 vc97ea6 v91419d (
  .v1215c2(w3),
  .v51ed6c(w13),
  .vc673c0(w15)
 );
 v0f6c39 vc7e44e (
  .v0bc190(w5),
  .vb09d88(w6),
  .ve1a6e8(w16)
 );
 vc97ea6 vda03c3 (
  .v1215c2(w6),
  .v51ed6c(w12),
  .vc673c0(w14)
 );
 va1ce30 v32065a (
  .vb9cfc3(w7),
  .v4642b6(w8),
  .v817794(w9),
  .v0550b6(w12),
  .v24708e(w13)
 );
 vdecca3 v23cb4f (
  .v55cd06(w9),
  .vbf8961(w10),
  .v2e2bd0(w11)
 );
endmodule

//---------------------------------------------------
//-- Adder-20bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Adder-20bits: Adder of two operands of 20 bits
//---------------------------------------------------
//---- Top entity
module vcb23aa (
 input [7:0] v39966a,
 input [7:0] veb2f59,
 output v4642b6,
 output [7:0] v62bf25
);
 wire [0:7] w0;
 wire [0:7] w1;
 wire [0:3] w2;
 wire [0:3] w3;
 wire [0:7] w4;
 wire w5;
 wire w6;
 wire [0:3] w7;
 wire [0:3] w8;
 wire [0:3] w9;
 wire [0:3] w10;
 assign w0 = veb2f59;
 assign w1 = v39966a;
 assign v62bf25 = w4;
 assign v4642b6 = w5;
 v6bdcd9 vd88c66 (
  .vcc8c7c(w0),
  .v651522(w9),
  .v2cc41f(w10)
 );
 v6bdcd9 v26a0bb (
  .vcc8c7c(w1),
  .v651522(w7),
  .v2cc41f(w8)
 );
 v25966b v9ea427 (
  .v817794(w3),
  .v4642b6(w6),
  .v0550b6(w8),
  .v24708e(w10)
 );
 vafb28f vc75346 (
  .v515fe7(w2),
  .v3c88fc(w3),
  .va9ac17(w4)
 );
 va1ce30 v40c17f (
  .v817794(w2),
  .v4642b6(w5),
  .vb9cfc3(w6),
  .v0550b6(w7),
  .v24708e(w9)
 );
endmodule

//---------------------------------------------------
//-- Adder-8bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Adder-8bits: Adder of two operands of 8 bits
//---------------------------------------------------
//---- Top entity
module v6bdcd9 (
 input [7:0] vcc8c7c,
 output [3:0] v651522,
 output [3:0] v2cc41f
);
 wire [0:3] w0;
 wire [0:3] w1;
 wire [0:7] w2;
 assign v651522 = w0;
 assign v2cc41f = w1;
 assign w2 = vcc8c7c;
 v6bdcd9_v9a2a06 v9a2a06 (
  .o1(w0),
  .o0(w1),
  .i(w2)
 );
endmodule

//---------------------------------------------------
//-- Bus8-Split-half
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus8-Split-half: Split the 8-bits bus into two buses of the same size
//---------------------------------------------------

module v6bdcd9_v9a2a06 (
 input [7:0] i,
 output [3:0] o1,
 output [3:0] o0
);
 assign o1 = i[7:4];
 assign o0 = i[3:0];
endmodule
//---- Top entity
module v25966b (
 input [3:0] v0550b6,
 input [3:0] v24708e,
 output v4642b6,
 output [3:0] v817794
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire [0:3] w5;
 wire [0:3] w6;
 wire [0:3] w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 assign w5 = v24708e;
 assign w6 = v0550b6;
 assign v817794 = w7;
 assign v4642b6 = w9;
 v1ea21d vdbe125 (
  .v4642b6(w0),
  .v8e8a67(w2),
  .v27dec4(w15),
  .v82de4f(w18)
 );
 vad119b vb8ad86 (
  .v0ef266(w0),
  .v8e8a67(w1),
  .v4642b6(w3),
  .v27dec4(w14),
  .v82de4f(w17)
 );
 vad119b v5d29b2 (
  .v0ef266(w3),
  .v8e8a67(w4),
  .v4642b6(w8),
  .v27dec4(w12),
  .v82de4f(w16)
 );
 vc4f23a vf4a6ff (
  .v985fcb(w5),
  .v4f1fd3(w13),
  .vda577d(w16),
  .v3f8943(w17),
  .v64d863(w18)
 );
 vc4f23a v9d4632 (
  .v985fcb(w6),
  .v4f1fd3(w11),
  .vda577d(w12),
  .v3f8943(w14),
  .v64d863(w15)
 );
 v84f0a1 v140dbf (
  .vee8a83(w1),
  .v03aaf0(w2),
  .vf8041d(w4),
  .v11bca5(w7),
  .vd84a57(w10)
 );
 vad119b v5c5937 (
  .v0ef266(w8),
  .v4642b6(w9),
  .v8e8a67(w10),
  .v27dec4(w11),
  .v82de4f(w13)
 );
endmodule

//---------------------------------------------------
//-- Adder-4bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Adder-4bits: Adder of two operands of 4 bits
//---------------------------------------------------
//---- Top entity
module v1ea21d (
 input v27dec4,
 input v82de4f,
 output v4642b6,
 output v8e8a67
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 assign w0 = v82de4f;
 assign w1 = v27dec4;
 assign v4642b6 = w3;
 assign v8e8a67 = w4;
 vad119b vb820a1 (
  .v82de4f(w0),
  .v27dec4(w1),
  .v0ef266(w2),
  .v4642b6(w3),
  .v8e8a67(w4)
 );
 vd30ca9 v23ebb6 (
  .v9fb85f(w2)
 );
endmodule

//---------------------------------------------------
//-- Adder-1bit
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Adder-1bit: Adder of two operands of 1 bit
//---------------------------------------------------
//---- Top entity
module vad119b (
 input v27dec4,
 input v82de4f,
 input v0ef266,
 output v4642b6,
 output v8e8a67
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 assign v8e8a67 = w1;
 assign v4642b6 = w5;
 assign w6 = v27dec4;
 assign w7 = v27dec4;
 assign w8 = v82de4f;
 assign w9 = v82de4f;
 assign w10 = v0ef266;
 assign w11 = v0ef266;
 assign w2 = w0;
 assign w7 = w6;
 assign w9 = w8;
 assign w11 = w10;
 vd12401 v2e3d9f (
  .vcbab45(w0),
  .v0e28cb(w7),
  .v3ca442(w9)
 );
 vd12401 vb50462 (
  .v0e28cb(w0),
  .vcbab45(w1),
  .v3ca442(w11)
 );
 vba518e v4882f4 (
  .v3ca442(w2),
  .vcbab45(w3),
  .v0e28cb(w10)
 );
 vba518e v8fcf41 (
  .vcbab45(w4),
  .v0e28cb(w6),
  .v3ca442(w8)
 );
 v873425 vc5b8b9 (
  .v3ca442(w3),
  .v0e28cb(w4),
  .vcbab45(w5)
 );
endmodule

//---------------------------------------------------
//-- AdderC-1bit
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- AdderC-1bit: Adder of two operands of 1 bit plus the carry in
//---------------------------------------------------
//---- Top entity
module vd12401 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 vd12401_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- XOR2
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- XOR gate: two bits input xor gate
//---------------------------------------------------

module vd12401_vf4938a (
 input a,
 input b,
 output c
);
 //-- XOR gate
 //-- Verilog implementation
 
 assign c = a ^ b;
 
endmodule
//---- Top entity
module v873425 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v873425_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- OR2
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- OR2: Two bits input OR gate
//---------------------------------------------------

module v873425_vf4938a (
 input a,
 input b,
 output c
);
 //-- OR Gate
 //-- Verilog implementation
 
 assign c = a | b;
 
 
endmodule
//---- Top entity
module vd30ca9 (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 vd30ca9_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

//---------------------------------------------------
//-- bit-0
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Constant bit 0
//---------------------------------------------------

module vd30ca9_vb2eccd (
 output q
);
 //-- Constant bit-0
 assign q = 1'b0;
 
 
endmodule
//---- Top entity
module vafb28f (
 input [3:0] v515fe7,
 input [3:0] v3c88fc,
 output [7:0] va9ac17
);
 wire [0:7] w0;
 wire [0:3] w1;
 wire [0:3] w2;
 assign va9ac17 = w0;
 assign w1 = v515fe7;
 assign w2 = v3c88fc;
 vafb28f_v9a2a06 v9a2a06 (
  .o(w0),
  .i1(w1),
  .i0(w2)
 );
endmodule

//---------------------------------------------------
//-- Bus8-Join-half
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus8-Join-half: Join the two same halves into an 8-bits Bus
//---------------------------------------------------

module vafb28f_v9a2a06 (
 input [3:0] i1,
 input [3:0] i0,
 output [7:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module va1ce30 (
 input [3:0] v0550b6,
 input [3:0] v24708e,
 input vb9cfc3,
 output v4642b6,
 output [3:0] v817794
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire [0:3] w5;
 wire [0:3] w6;
 wire [0:3] w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 wire w19;
 assign w5 = v24708e;
 assign w6 = v0550b6;
 assign v817794 = w7;
 assign v4642b6 = w9;
 assign w11 = vb9cfc3;
 vad119b vb8ad86 (
  .v0ef266(w0),
  .v8e8a67(w1),
  .v4642b6(w3),
  .v27dec4(w15),
  .v82de4f(w18)
 );
 vad119b v5d29b2 (
  .v0ef266(w3),
  .v8e8a67(w4),
  .v4642b6(w8),
  .v27dec4(w13),
  .v82de4f(w17)
 );
 vc4f23a vf4a6ff (
  .v985fcb(w5),
  .v4f1fd3(w14),
  .vda577d(w17),
  .v3f8943(w18),
  .v64d863(w19)
 );
 vc4f23a v9d4632 (
  .v985fcb(w6),
  .v4f1fd3(w12),
  .vda577d(w13),
  .v3f8943(w15),
  .v64d863(w16)
 );
 v84f0a1 v140dbf (
  .vee8a83(w1),
  .v03aaf0(w2),
  .vf8041d(w4),
  .v11bca5(w7),
  .vd84a57(w10)
 );
 vad119b v5c5937 (
  .v0ef266(w8),
  .v4642b6(w9),
  .v8e8a67(w10),
  .v27dec4(w12),
  .v82de4f(w14)
 );
 vad119b v3599be (
  .v4642b6(w0),
  .v8e8a67(w2),
  .v0ef266(w11),
  .v27dec4(w16),
  .v82de4f(w19)
 );
endmodule

//---------------------------------------------------
//-- AdderC-4bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- AdderC-4bits: Adder of two operands of 4 bits and Carry in
//---------------------------------------------------
//---- Top entity
module vc3c498 (
 input [7:0] v45c6ee,
 input [7:0] v20212e,
 input vb9cfc3,
 output v4642b6,
 output [7:0] veeaa8e
);
 wire w0;
 wire w1;
 wire [0:7] w2;
 wire [0:7] w3;
 wire [0:7] w4;
 wire [0:3] w5;
 wire [0:3] w6;
 wire w7;
 wire [0:3] w8;
 wire [0:3] w9;
 wire [0:3] w10;
 wire [0:3] w11;
 assign w1 = vb9cfc3;
 assign w2 = v45c6ee;
 assign w3 = v20212e;
 assign veeaa8e = w4;
 assign v4642b6 = w7;
 v6bdcd9 v8d795a (
  .vcc8c7c(w3),
  .v651522(w10),
  .v2cc41f(w11)
 );
 v6bdcd9 v23dbc5 (
  .vcc8c7c(w2),
  .v651522(w8),
  .v2cc41f(w9)
 );
 vafb28f vef3a58 (
  .va9ac17(w4),
  .v3c88fc(w5),
  .v515fe7(w6)
 );
 va1ce30 v0ff71a (
  .v4642b6(w0),
  .vb9cfc3(w1),
  .v817794(w5),
  .v0550b6(w9),
  .v24708e(w11)
 );
 va1ce30 v12f94f (
  .vb9cfc3(w0),
  .v817794(w6),
  .v4642b6(w7),
  .v0550b6(w8),
  .v24708e(w10)
 );
endmodule

//---------------------------------------------------
//-- AdderC-8bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- AdderC-8bits: Adder of two operands of 8 bits and Carry in
//---------------------------------------------------
//---- Top entity
module v8cc49c (
 input [7:0] vb334ae,
 input [7:0] v2b8a97,
 output [15:0] v14a530
);
 wire [0:15] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 assign v14a530 = w0;
 assign w1 = v2b8a97;
 assign w2 = vb334ae;
 v8cc49c_v9a2a06 v9a2a06 (
  .o(w0),
  .i0(w1),
  .i1(w2)
 );
endmodule

//---------------------------------------------------
//-- Bus16-Join-half
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus16-Join-half: Join the two same halves into an 16-bits Bus
//---------------------------------------------------

module v8cc49c_v9a2a06 (
 input [7:0] i1,
 input [7:0] i0,
 output [15:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module v0f6c39 (
 input [19:0] v0bc190,
 output [11:0] vb09d88,
 output [7:0] ve1a6e8
);
 wire [0:19] w0;
 wire [0:7] w1;
 wire [0:11] w2;
 assign w0 = v0bc190;
 assign ve1a6e8 = w1;
 assign vb09d88 = w2;
 v0f6c39_v9a2a06 v9a2a06 (
  .i(w0),
  .o0(w1),
  .o1(w2)
 );
endmodule

//---------------------------------------------------
//-- Bus20-Split-12-8
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus20-Split-8-12: Split the 20-bits bus into two buses of 8 and 12 wires
//---------------------------------------------------

module v0f6c39_v9a2a06 (
 input [19:0] i,
 output [11:0] o1,
 output [7:0] o0
);
 assign o1 = i[19:8];
 assign o0 = i[7:0];
endmodule
//---- Top entity
module vc97ea6 (
 input [11:0] v1215c2,
 output [3:0] v51ed6c,
 output [7:0] vc673c0
);
 wire [0:3] w0;
 wire [0:11] w1;
 wire [0:7] w2;
 assign v51ed6c = w0;
 assign w1 = v1215c2;
 assign vc673c0 = w2;
 vc97ea6_v9a2a06 v9a2a06 (
  .o1(w0),
  .i(w1),
  .o0(w2)
 );
endmodule

//---------------------------------------------------
//-- Bus12-Split-4-8
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus12-Split-4-8: Split the 12-bits bus into two buses of 4 and 8 wires
//---------------------------------------------------

module vc97ea6_v9a2a06 (
 input [11:0] i,
 output [3:0] o1,
 output [7:0] o0
);
 
 assign o1 = i[11:8];
 assign o0 = i[7:0];
endmodule
//---- Top entity
module vb9ddd5 (
 input [19:0] vdb40a4,
 input [19:0] v07eb94,
 output v4642b6
);
 wire w0;
 wire [0:19] w1;
 wire [0:19] w2;
 wire w3;
 wire w4;
 wire w5;
 wire [0:3] w6;
 wire [0:7] w7;
 wire [0:7] w8;
 wire [0:3] w9;
 wire [0:7] w10;
 wire [0:7] w11;
 assign v4642b6 = w0;
 assign w1 = v07eb94;
 assign w2 = vdb40a4;
 vb2762a vb6832a (
  .v4642b6(w3),
  .v715730(w8),
  .vf191e6(w11)
 );
 vb2762a v302658 (
  .v4642b6(w4),
  .v715730(w7),
  .vf191e6(w10)
 );
 v2dbbdf vb63230 (
  .v0bc190(w1),
  .v906d8f(w9),
  .v89b162(w10),
  .ve1a6e8(w11)
 );
 v2dbbdf veb4dc0 (
  .v0bc190(w2),
  .v906d8f(w6),
  .v89b162(w7),
  .ve1a6e8(w8)
 );
 v438230 vc72070 (
  .v4642b6(w5),
  .v693354(w6),
  .v5369cd(w9)
 );
 vae245c v9196c7 (
  .vcbab45(w0),
  .v3ca442(w3),
  .v0e28cb(w4),
  .v033bf6(w5)
 );
endmodule

//---------------------------------------------------
//-- comp2-20bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Comp2-20bit: Comparator of two 20-bit numbers
//---------------------------------------------------
//---- Top entity
module vb2762a (
 input [7:0] v715730,
 input [7:0] vf191e6,
 output v4642b6
);
 wire w0;
 wire w1;
 wire w2;
 wire [0:7] w3;
 wire [0:7] w4;
 wire [0:3] w5;
 wire [0:3] w6;
 wire [0:3] w7;
 wire [0:3] w8;
 assign v4642b6 = w0;
 assign w3 = v715730;
 assign w4 = vf191e6;
 v438230 v577a36 (
  .v4642b6(w2),
  .v693354(w6),
  .v5369cd(w8)
 );
 vba518e v707c6e (
  .vcbab45(w0),
  .v0e28cb(w1),
  .v3ca442(w2)
 );
 v6bdcd9 v921a9f (
  .vcc8c7c(w4),
  .v651522(w7),
  .v2cc41f(w8)
 );
 v6bdcd9 v8cfa4d (
  .vcc8c7c(w3),
  .v651522(w5),
  .v2cc41f(w6)
 );
 v438230 vfc1765 (
  .v4642b6(w1),
  .v693354(w5),
  .v5369cd(w7)
 );
endmodule

//---------------------------------------------------
//-- comp2-8bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Comp2-8bit: Comparator of two 8-bit numbers
//---------------------------------------------------
//---- Top entity
module v438230 (
 input [3:0] v693354,
 input [3:0] v5369cd,
 output v4642b6
);
 wire w0;
 wire [0:3] w1;
 wire [0:3] w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 assign v4642b6 = w0;
 assign w1 = v693354;
 assign w2 = v5369cd;
 v23b15b v09a5a5 (
  .v4642b6(w3),
  .v27dec4(w12),
  .v6848e9(w14)
 );
 v23b15b vc1b29d (
  .v4642b6(w4),
  .v27dec4(w11),
  .v6848e9(w13)
 );
 v23b15b vcd27ce (
  .v4642b6(w5),
  .v27dec4(w9),
  .v6848e9(w10)
 );
 vc4f23a vea9c80 (
  .v985fcb(w1),
  .v4f1fd3(w7),
  .vda577d(w9),
  .v3f8943(w11),
  .v64d863(w12)
 );
 vc4f23a va7dcdc (
  .v985fcb(w2),
  .v4f1fd3(w8),
  .vda577d(w10),
  .v3f8943(w13),
  .v64d863(w14)
 );
 v23b15b va0849c (
  .v4642b6(w6),
  .v27dec4(w7),
  .v6848e9(w8)
 );
 veffd42 v6e3e65 (
  .vcbab45(w0),
  .v3ca442(w3),
  .v0e28cb(w4),
  .v033bf6(w5),
  .v9eb652(w6)
 );
endmodule

//---------------------------------------------------
//-- comp2-4bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Comp2-4bit: Comparator of two 4-bit numbers
//---------------------------------------------------
//---- Top entity
module v23b15b (
 input v27dec4,
 input v6848e9,
 output v4642b6
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 assign w1 = v27dec4;
 assign v4642b6 = w2;
 assign w3 = v6848e9;
 vd12401 v955b2b (
  .vcbab45(w0),
  .v0e28cb(w1),
  .v3ca442(w3)
 );
 v3676a0 vf92936 (
  .v0e28cb(w0),
  .vcbab45(w2)
 );
endmodule

//---------------------------------------------------
//-- comp2-1bit
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Comp2-1bit: Comparator of two 1-bit numbers
//---------------------------------------------------
//---- Top entity
module veffd42 (
 input v9eb652,
 input v033bf6,
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 assign w0 = v3ca442;
 assign w1 = v9eb652;
 assign w2 = v033bf6;
 assign w3 = v0e28cb;
 assign vcbab45 = w4;
 vba518e vf3ef0f (
  .v3ca442(w0),
  .v0e28cb(w3),
  .vcbab45(w6)
 );
 vba518e vdcc53d (
  .v0e28cb(w1),
  .v3ca442(w2),
  .vcbab45(w5)
 );
 vba518e v17ac22 (
  .vcbab45(w4),
  .v0e28cb(w5),
  .v3ca442(w6)
 );
endmodule

//---------------------------------------------------
//-- AND4
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Three bits input And gate
//---------------------------------------------------
//---- Top entity
module v2dbbdf (
 input [19:0] v0bc190,
 output [3:0] v906d8f,
 output [7:0] v89b162,
 output [7:0] ve1a6e8
);
 wire [0:19] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 wire [0:3] w3;
 assign w0 = v0bc190;
 assign ve1a6e8 = w1;
 assign v89b162 = w2;
 assign v906d8f = w3;
 v2dbbdf_v9a2a06 v9a2a06 (
  .i(w0),
  .o0(w1),
  .o1(w2),
  .o2(w3)
 );
endmodule

//---------------------------------------------------
//-- Bus20-Split-4-8-8
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus20-Split-4-8-8: Split the 20-bits bus into three buses of 4, 8 and 8 wires
//---------------------------------------------------

module v2dbbdf_v9a2a06 (
 input [19:0] i,
 output [3:0] o2,
 output [7:0] o1,
 output [7:0] o0
);
 assign o2 = i[19:16];
 assign o1 = i[15:8];
 assign o0 = i[7:0];
endmodule
//---- Top entity
module vae245c (
 input v033bf6,
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 assign w0 = v033bf6;
 assign w1 = v0e28cb;
 assign w2 = v3ca442;
 assign vcbab45 = w4;
 vba518e v19b5b0 (
  .v0e28cb(w0),
  .v3ca442(w1),
  .vcbab45(w3)
 );
 vba518e vf3ef0f (
  .v3ca442(w2),
  .v0e28cb(w3),
  .vcbab45(w4)
 );
endmodule

//---------------------------------------------------
//-- AND3
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Three bits input And gate
//---------------------------------------------------
//---- Top entity
module v1bc657 (
 input [19:0] v0e4f6c,
 input [19:0] v0a4fd8,
 output v4642b6
);
 wire [0:19] w0;
 wire [0:19] w1;
 wire w2;
 assign w0 = v0e4f6c;
 assign w1 = v0a4fd8;
 assign v4642b6 = w2;
 v1bc657_v863693 v863693 (
  .a(w0),
  .b(w1),
  .o(w2)
 );
endmodule

//---------------------------------------------------
//-- less-eq-20bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Less-eq-20bit: Comparator of two 20-bit numbers
//---------------------------------------------------

module v1bc657_v863693 (
 input [19:0] a,
 input [19:0] b,
 output o
);
 assign o = (a <= b);
endmodule
//---- Top entity
module ve2cdb0 #(
 parameter vb36a78 = "vb36a78.list"
) (
 input [3:0] v851180,
 output [19:0] vfde47f
);
 localparam p0 = vb36a78;
 wire [0:3] w1;
 wire [0:19] w2;
 assign w1 = v851180;
 assign vfde47f = w2;
 ve2cdb0_v361fe9 #(
  .DATA(p0)
 ) v361fe9 (
  .i(w1),
  .q(w2)
 );
endmodule

//---------------------------------------------------
//-- mi-tabla4-20
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Circuito combinacional de 4 entradas y 20 salidas
//---------------------------------------------------

module ve2cdb0_v361fe9 #(
 parameter DATA = 0
) (
 input [3:0] i,
 output [19:0] q
);
 
 //-- Bits del bus de entrada
 localparam N = 4;
 
 //-- Bits del bus de salida
 localparam M = 20;
 
 //-- Calcular tamaño de la tabla
 //-- (filas) segun los bits de entrada
 localparam TAM = 2 ** N;
 
 //-- Definición de la tabla
 //-- Tabla de TAM elementos de M bits
 reg [M-1:0] tabla[0:TAM-1];
 
 //-- Read the table
 assign q = tabla[i];
 
 //-- Init table from DATA parameters
 initial begin
   if (DATA) $readmemh(DATA, tabla);
 end
endmodule
//---- Top entity
module va8938c #(
 parameter v7245c7 = 3,
 parameter vd63c4a = 0,
 parameter v4365a5 = 0,
 parameter v4ae06c = 1,
 parameter vd73ba5 = -1
) (
 input v64da9b,
 input v27dec4,
 input v7e359d,
 output [1:0] v585e5b,
 output v4642b6
);
 localparam p0 = v7245c7;
 localparam p2 = vd63c4a;
 localparam p10 = v4ae06c;
 localparam p11 = vd73ba5;
 localparam p13 = v4365a5;
 wire w1;
 wire w3;
 wire [0:1] w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire [0:1] w12;
 wire w14;
 wire w15;
 wire [0:1] w16;
 wire [0:1] w17;
 wire [0:1] w18;
 wire [0:1] w19;
 wire [0:1] w20;
 wire w21;
 wire w22;
 wire [0:1] w23;
 wire w24;
 wire w25;
 assign w8 = v27dec4;
 assign w9 = v7e359d;
 assign v585e5b = w12;
 assign v4642b6 = w15;
 assign w21 = v64da9b;
 assign w22 = v64da9b;
 assign w14 = w6;
 assign w17 = w12;
 assign w18 = w12;
 assign w18 = w17;
 assign w19 = w12;
 assign w19 = w17;
 assign w19 = w18;
 assign w20 = w12;
 assign w20 = w17;
 assign w20 = w18;
 assign w20 = w19;
 assign w22 = w21;
 v975cb2 #(
  .v16d6b8(p0)
 ) vac80cd (
  .v18e78c(w1),
  .vea9fae(w19)
 );
 vb2090f vca3c68 (
  .v0e28cb(w1),
  .v3ca442(w8),
  .vcbab45(w24)
 );
 vae2422 #(
  .v16d6b8(p2)
 ) v1f8898 (
  .v18e78c(w3),
  .vea9fae(w20)
 );
 vb2090f vb16a78 (
  .v0e28cb(w3),
  .v3ca442(w9),
  .vcbab45(w25)
 );
 vf39d82 #(
  .v422d28(p13)
 ) v984be0 (
  .v568b8a(w4),
  .vf892a0(w6),
  .va484f0(w12),
  .v41eb95(w21)
 );
 veebee1 v10a720 (
  .v7fb9b3(w4),
  .v50d6c6(w5),
  .vc9d156(w16),
  .v340b68(w23)
 );
 vaa7742 v587b0e (
  .vb4d15b(w5),
  .va30e2e(w7),
  .vccf27c(w24),
  .ve229dd(w25)
 );
 v35f267 v57c556 (
  .vcbab45(w6),
  .v0e28cb(w7)
 );
 v81be9d #(
  .v8d305c(p10)
 ) v47efb9 (
  .vb5a0f8(w16),
  .v1b2204(w17)
 );
 v81be9d #(
  .v8d305c(p11)
 ) v8e8eb6 (
  .v1b2204(w18),
  .vb5a0f8(w23)
 );
 v1c7dae v8ee2bb (
  .vf54559(w14),
  .ve8318d(w15),
  .va4102a(w22)
 );
endmodule

//---------------------------------------------------
//-- count-up-dn-lim
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 2bits up-down counter with limits
//---------------------------------------------------
//---- Top entity
module v975cb2 #(
 parameter v16d6b8 = 1
) (
 input [1:0] vea9fae,
 output v18e78c
);
 localparam p1 = v16d6b8;
 wire w0;
 wire [0:1] w2;
 assign v18e78c = w0;
 assign w2 = vea9fae;
 v975cb2_vd75681 #(
  .B(p1)
 ) vd75681 (
  .eq(w0),
  .a(w2)
 );
endmodule

//---------------------------------------------------
//-- Menor-que-1-op
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Comparador menor que, de un operando de 2 bits
//---------------------------------------------------

module v975cb2_vd75681 #(
 parameter B = 0
) (
 input [1:0] a,
 output eq
);
 assign eq = (a < B);
endmodule
//---- Top entity
module vb2090f (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 vb2090f_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- AND
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Puerta AND
//---------------------------------------------------

module vb2090f_vf4938a (
 input a,
 input b,
 output c
);
 //-- Puerta AND
 
 //-- module and (input wire a, input wire b,
 //--             output wire c);
 
 assign c = a & b;
 
 //-- endmodule
endmodule
//---- Top entity
module vae2422 #(
 parameter v16d6b8 = 1
) (
 input [1:0] vea9fae,
 output v18e78c
);
 localparam p1 = v16d6b8;
 wire w0;
 wire [0:1] w2;
 assign v18e78c = w0;
 assign w2 = vea9fae;
 vae2422_vd75681 #(
  .B(p1)
 ) vd75681 (
  .eq(w0),
  .a(w2)
 );
endmodule

//---------------------------------------------------
//-- Greather-than-2bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 2bits-Greather than comparator
//---------------------------------------------------

module vae2422_vd75681 #(
 parameter B = 0
) (
 input [1:0] a,
 output eq
);
 assign eq = (a > B);
endmodule
//---- Top entity
module vf39d82 #(
 parameter v422d28 = 0
) (
 input v41eb95,
 input [1:0] v568b8a,
 input vf892a0,
 output [1:0] va484f0
);
 localparam p0 = v422d28;
 wire w1;
 wire w2;
 wire [0:1] w3;
 wire [0:1] w4;
 assign w1 = vf892a0;
 assign w2 = v41eb95;
 assign w3 = v568b8a;
 assign va484f0 = w4;
 vf39d82_v9148cb #(
  .INI(p0)
 ) v9148cb (
  .load(w1),
  .clk(w2),
  .d(w3),
  .q(w4)
 );
endmodule

//---------------------------------------------------
//-- Registro
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Registro de 2 bits
//---------------------------------------------------

module vf39d82_v9148cb #(
 parameter INI = 0
) (
 input clk,
 input [1:0] d,
 input load,
 output [1:0] q
);
 localparam N = 2;
 
 reg [N-1:0] q = INI;
 
 always @(posedge clk)
   if (load)
     q <= d;
endmodule
//---- Top entity
module veebee1 (
 input [1:0] vc9d156,
 input [1:0] v340b68,
 input v50d6c6,
 output [1:0] v7fb9b3
);
 wire w0;
 wire [0:1] w1;
 wire [0:1] w2;
 wire [0:1] w3;
 assign w0 = v50d6c6;
 assign v7fb9b3 = w1;
 assign w2 = vc9d156;
 assign w3 = v340b68;
 veebee1_ve4e0df ve4e0df (
  .sel(w0),
  .o(w1),
  .i1(w2),
  .i0(w3)
 );
endmodule

//---------------------------------------------------
//-- Mux 2 a 1 de 2 bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Multiplexor de 2 a 1 de 2 bits
//---------------------------------------------------

module veebee1_ve4e0df (
 input [1:0] i1,
 input [1:0] i0,
 input sel,
 output [1:0] o
);
 //-- Multiplexor de 2 a 1, 
 //-- de 2 bits
 
 reg [1:0] o;
 
 always @(*) begin
     case(sel)
         0: o = i0;
         1: o = i1;
         default: o = i0;
     endcase
 end
 
 
endmodule
//---- Top entity
module vaa7742 (
 input vccf27c,
 input ve229dd,
 output vb4d15b,
 output va30e2e
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 assign w0 = ve229dd;
 assign w1 = vccf27c;
 assign vb4d15b = w2;
 assign va30e2e = w3;
 vaa7742_v4407ca v4407ca (
  .i0(w0),
  .i1(w1),
  .y(w2),
  .zero(w3)
 );
endmodule

//---------------------------------------------------
//-- Codificador-2-1
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Codificador de 2 a 1. La salida zero se activa cuando ninguna entrada está activada
//---------------------------------------------------

module vaa7742_v4407ca (
 input i1,
 input i0,
 output y,
 output zero
);
 //-- Codificador de 2 a 1
 
 assign zero = ({i1,i0}==2'b00);
 assign y = (i1 == 1);
 
endmodule
//---- Top entity
module v35f267 (
 input v0e28cb,
 output vcbab45
);
 wire w0;
 wire w1;
 assign w0 = v0e28cb;
 assign vcbab45 = w1;
 v35f267_vd54ca1 vd54ca1 (
  .a(w0),
  .c(w1)
 );
endmodule

//---------------------------------------------------
//-- NOT
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Puerta NOT
//---------------------------------------------------

module v35f267_vd54ca1 (
 input a,
 output c
);
 //-- Puerta NOT
 
 //-- module (input wire a, output wire c);
 
 
 assign c = ~a;
 
 
 //-- endmodule
 
endmodule
//---- Top entity
module v81be9d #(
 parameter v8d305c = 1
) (
 input [1:0] v1b2204,
 output [1:0] vb5a0f8
);
 localparam p0 = v8d305c;
 wire [0:1] w1;
 wire [0:1] w2;
 assign w1 = v1b2204;
 assign vb5a0f8 = w2;
 v81be9d_va0c26a #(
  .k(p0)
 ) va0c26a (
  .a(w1),
  .s(w2)
 );
endmodule

//---------------------------------------------------
//-- sum-1op-2bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Sumador de un operando de 2 bits con una constante pasada como parámetro (No hay accarreo)
//---------------------------------------------------

module v81be9d_va0c26a #(
 parameter k = 0
) (
 input [1:0] a,
 output [1:0] s
);
 assign s = a + k;
endmodule
//---- Top entity
module v1c7dae #(
 parameter v71e305 = 0
) (
 input va4102a,
 input vf54559,
 output ve8318d
);
 localparam p2 = v71e305;
 wire w0;
 wire w1;
 wire w3;
 assign w0 = va4102a;
 assign ve8318d = w1;
 assign w3 = vf54559;
 v1c7dae_vb8adf8 #(
  .INI(p2)
 ) vb8adf8 (
  .clk(w0),
  .q(w1),
  .d(w3)
 );
endmodule

//---------------------------------------------------
//-- Biestable-D
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Biestable de datos (Tipo D). Cuando se recibe un tic por load se captura el dato
//---------------------------------------------------

module v1c7dae_vb8adf8 #(
 parameter INI = 0
) (
 input clk,
 input d,
 output q
);
 reg q = INI;
 always @(posedge clk)
   q <= d;
endmodule
//---- Top entity
module v0dbcb9 (
 input [1:0] v8b19dd,
 output v3f8943,
 output v64d863
);
 wire w0;
 wire w1;
 wire [0:1] w2;
 assign v3f8943 = w0;
 assign v64d863 = w1;
 assign w2 = v8b19dd;
 v0dbcb9_v9a2a06 v9a2a06 (
  .o1(w0),
  .o0(w1),
  .i(w2)
 );
endmodule

//---------------------------------------------------
//-- Bus2-Split-all
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus2-Split-all: Split the 2-bits bus into two wires
//---------------------------------------------------

module v0dbcb9_v9a2a06 (
 input [1:0] i,
 output o1,
 output o0
);
 assign o1 = i[1];
 assign o0 = i[0];
endmodule
//---- Top entity
module v888484 #(
 parameter v9d2d5b = 0,
 parameter v42e61f = 0
) (
 input vfde3d7,
 input vd9601b,
 output v157a67,
 output v64879c
);
 localparam p4 = v9d2d5b;
 localparam p5 = v42e61f;
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w6;
 wire w7;
 assign w0 = vd9601b;
 assign v157a67 = w1;
 assign v64879c = w3;
 assign w6 = vfde3d7;
 assign w7 = vfde3d7;
 assign w2 = w1;
 assign w7 = w6;
 v31e84e v9cfc0f (
  .ve78ab8(w2),
  .v3487af(w3),
  .ved8395(w7)
 );
 v0b641d #(
  .v17ea21(p4),
  .v803182(p5)
 ) v6ca512 (
  .v27dec4(w0),
  .v4642b6(w1),
  .v25ab12(w6)
 );
endmodule

//---------------------------------------------------
//-- Button-tic
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Button-tic: Configurable button that emits a tic when it is pressed
//---------------------------------------------------
//---- Top entity
module v31e84e (
 input ved8395,
 input ve78ab8,
 output v3487af
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 assign w0 = ve78ab8;
 assign w1 = ved8395;
 assign w4 = ve78ab8;
 assign v3487af = w5;
 assign w4 = w0;
 v053dc2 v1bde40 (
  .vf54559(w0),
  .va4102a(w1),
  .ve8318d(w2)
 );
 v3676a0 v9d4cda (
  .v0e28cb(w2),
  .vcbab45(w3)
 );
 vba518e v57aa83 (
  .v0e28cb(w3),
  .v3ca442(w4),
  .vcbab45(w5)
 );
endmodule

//---------------------------------------------------
//-- Rising-edge-detector
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Rising-edge detector. It generates a 1-period pulse (tic) when a rising edge is detected on the input
//---------------------------------------------------
//---- Top entity
module v0b641d #(
 parameter v17ea21 = 0,
 parameter v803182 = 0
) (
 input v25ab12,
 input v27dec4,
 output v4642b6
);
 localparam p2 = v803182;
 localparam p4 = v17ea21;
 wire w0;
 wire w1;
 wire w3;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 assign v4642b6 = w5;
 assign w6 = v27dec4;
 assign w7 = v25ab12;
 assign w8 = v25ab12;
 assign w8 = w7;
 v6c3aff #(
  .v2fb6e5(p4)
 ) v67ee04 (
  .v758f58(w0),
  .vedbc89(w6)
 );
 vf718a5 v5e6bb3 (
  .v6a82dd(w3),
  .vd4e5d7(w5),
  .v444878(w8)
 );
 vdc93d6 v71ab2a (
  .ve7f5e6(w0),
  .v3c12b5(w1),
  .v717e81(w7)
 );
 vad96dc #(
  .v6a9fe4(p2)
 ) vc0a9e9 (
  .v27dec4(w1),
  .v4642b6(w3)
 );
endmodule

//---------------------------------------------------
//-- Button
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Configurable button (pull-up on/off. Not on/off)
//---------------------------------------------------
//---- Top entity
module v6c3aff #(
 parameter v2fb6e5 = 1
) (
 input vedbc89,
 output v758f58
);
 localparam p2 = v2fb6e5;
 wire w0;
 wire w1;
 assign w0 = vedbc89;
 assign v758f58 = w1;
 v6c3aff_v34955f #(
  .ON(p2)
 ) v34955f (
  .i(w0),
  .o(w1)
 );
endmodule

//---------------------------------------------------
//-- Pull-upx1
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- FPGA internal pull-up configuration on the input port
//---------------------------------------------------

module v6c3aff_v34955f #(
 parameter ON = 0
) (
 input i,
 output o
);
 // 1-Pull up
 
 //-- Place the IO block, configured as  
 //-- input with pull-up
 SB_IO
   #(
     .PIN_TYPE(6'b 1010_01),
     
     //-- The pull-up is activated or not
     //-- depeding on the ON parameter
     .PULLUP(ON)
     
   ) input_pin (
 
     //--- Input pin
     .PACKAGE_PIN(i),
     
     //-- Block output
     .D_IN_0(o),
     
     //-- Configured as input
     .OUTPUT_ENABLE(1'b0),
     
     //-- Not used
     .D_OUT_0(1'b0)
   );
endmodule
//---- Top entity
module vf718a5 (
 input v444878,
 input v6a82dd,
 output vd4e5d7
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 assign w2 = v444878;
 assign w3 = v444878;
 assign w4 = v444878;
 assign vd4e5d7 = w5;
 assign w6 = v6a82dd;
 assign w7 = v6a82dd;
 assign w3 = w2;
 assign w4 = w2;
 assign w4 = w3;
 assign w7 = w6;
 v93adf6 ve5d8ab (
  .v9afc1f(w0),
  .va4102a(w2),
  .ve8318d(w5),
  .vf54559(w6)
 );
 v413e4a v93d042 (
  .ve37344(w0),
  .ve556f1(w1),
  .v6dda25(w3)
 );
 v332488 vf5eed3 (
  .v3487af(w1),
  .ved8395(w4),
  .ve78ab8(w7)
 );
endmodule

//---------------------------------------------------
//-- Debouncer-x01
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Remove the rebound on a mechanical switch
//---------------------------------------------------
//---- Top entity
module v93adf6 #(
 parameter v71e305 = 0
) (
 input va4102a,
 input vf54559,
 input v9afc1f,
 output ve8318d
);
 localparam p2 = v71e305;
 wire w0;
 wire w1;
 wire w3;
 wire w4;
 assign w0 = va4102a;
 assign ve8318d = w1;
 assign w3 = vf54559;
 assign w4 = v9afc1f;
 v93adf6_vb8adf8 #(
  .INI(p2)
 ) vb8adf8 (
  .clk(w0),
  .q(w1),
  .d(w3),
  .load(w4)
 );
endmodule

//---------------------------------------------------
//-- Reg-1bit
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 1bit register (implemented in verilog)
//---------------------------------------------------

module v93adf6_vb8adf8 #(
 parameter INI = 0
) (
 input clk,
 input d,
 input load,
 output q
);
 reg q = INI;
 
 always @(posedge clk)
   if (load)
     q <= d;
endmodule
//---- Top entity
module v413e4a (
 input v6dda25,
 input ve556f1,
 output [15:0] v49911e,
 output ve37344
);
 wire w0;
 wire [0:15] w1;
 wire [0:15] w2;
 wire w3;
 wire [0:15] w4;
 wire w5;
 assign w0 = ve556f1;
 assign w3 = v6dda25;
 assign v49911e = w4;
 assign ve37344 = w5;
 assign w4 = w1;
 vbc711b v8fa00b (
  .v782748(w0),
  .v3f90b8(w1),
  .vc320da(w2),
  .v6dda25(w3)
 );
 v8ecd59 v9392cd (
  .v2f9d57(w1),
  .vd7988b(w2),
  .v4642b6(w5)
 );
endmodule

//---------------------------------------------------
//-- syscounter-rst-16bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 16-bits Syscounter with reset
//---------------------------------------------------
//---- Top entity
module v8ecd59 #(
 parameter v6c5139 = 1
) (
 input [15:0] v2f9d57,
 output v4642b6,
 output [15:0] vd7988b
);
 localparam p1 = v6c5139;
 wire w0;
 wire [0:15] w2;
 wire [0:15] w3;
 assign v4642b6 = w0;
 assign w2 = v2f9d57;
 assign vd7988b = w3;
 v265696 #(
  .vd73390(p1)
 ) v76123a (
  .v4642b6(w0),
  .v36f2dd(w2),
  .vc068fb(w3)
 );
endmodule

//---------------------------------------------------
//-- Inc1-16bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Inc1-16bit: Increment a 16-bits number by one
//---------------------------------------------------
//---- Top entity
module v265696 #(
 parameter vd73390 = 0
) (
 input [15:0] v36f2dd,
 output v4642b6,
 output [15:0] vc068fb
);
 localparam p1 = vd73390;
 wire w0;
 wire [0:15] w2;
 wire [0:15] w3;
 wire [0:15] w4;
 assign v4642b6 = w0;
 assign w3 = v36f2dd;
 assign vc068fb = w4;
 v651fa3 #(
  .vc5c8ea(p1)
 ) vdd8fa2 (
  .vcd9338(w2)
 );
 vbc66d7 vce7ab7 (
  .v4642b6(w0),
  .v1489e0(w2),
  .v603a9a(w3),
  .v2c4251(w4)
 );
endmodule

//---------------------------------------------------
//-- AdderK-16bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- AdderK-16bit: Adder of 16-bit operand and 16-bit constant
//---------------------------------------------------
//---- Top entity
module v651fa3 #(
 parameter vc5c8ea = 0
) (
 output [15:0] vcd9338
);
 localparam p0 = vc5c8ea;
 wire [0:15] w1;
 assign vcd9338 = w1;
 v651fa3_v465065 #(
  .VALUE(p0)
 ) v465065 (
  .k(w1)
 );
endmodule

//---------------------------------------------------
//-- 16-bits-gen-constant
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Generic: 16-bits generic constant
//---------------------------------------------------

module v651fa3_v465065 #(
 parameter VALUE = 0
) (
 output [15:0] k
);
 assign k = VALUE;
endmodule
//---- Top entity
module vbc66d7 (
 input [15:0] v1489e0,
 input [15:0] v603a9a,
 output v4642b6,
 output [15:0] v2c4251
);
 wire w0;
 wire w1;
 wire [0:15] w2;
 wire [0:15] w3;
 wire [0:15] w4;
 wire [0:7] w5;
 wire [0:7] w6;
 wire [0:7] w7;
 wire [0:7] w8;
 wire [0:7] w9;
 wire [0:7] w10;
 assign v4642b6 = w0;
 assign w2 = v603a9a;
 assign w3 = v1489e0;
 assign v2c4251 = w4;
 v306ca3 v0a29fe (
  .v91b9c1(w2),
  .vef5eee(w9),
  .vd3ef3b(w10)
 );
 v306ca3 vb0a6ce (
  .v91b9c1(w3),
  .vef5eee(w7),
  .vd3ef3b(w8)
 );
 vcb23aa v8e0bba (
  .v4642b6(w1),
  .v62bf25(w6),
  .v39966a(w8),
  .veb2f59(w10)
 );
 vc3c498 v917bbf (
  .v4642b6(w0),
  .vb9cfc3(w1),
  .veeaa8e(w5),
  .v45c6ee(w7),
  .v20212e(w9)
 );
 v8cc49c v03c3e3 (
  .v14a530(w4),
  .vb334ae(w5),
  .v2b8a97(w6)
 );
endmodule

//---------------------------------------------------
//-- Adder-16bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Adder-16bits: Adder of two operands of 16 bits
//---------------------------------------------------
//---- Top entity
module v306ca3 (
 input [15:0] v91b9c1,
 output [7:0] vef5eee,
 output [7:0] vd3ef3b
);
 wire [0:15] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 assign w0 = v91b9c1;
 assign vef5eee = w1;
 assign vd3ef3b = w2;
 v306ca3_v9a2a06 v9a2a06 (
  .i(w0),
  .o1(w1),
  .o0(w2)
 );
endmodule

//---------------------------------------------------
//-- Bus16-Split-half
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus16-Split-half: Split the 16-bits bus into two buses of the same size
//---------------------------------------------------

module v306ca3_v9a2a06 (
 input [15:0] i,
 output [7:0] o1,
 output [7:0] o0
);
 assign o1 = i[15:8];
 assign o0 = i[7:0];
endmodule
//---- Top entity
module v332488 (
 input ved8395,
 input ve78ab8,
 output v3487af
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 assign w0 = ve78ab8;
 assign w1 = ved8395;
 assign v3487af = w2;
 assign w4 = ve78ab8;
 assign w4 = w0;
 vd12401 v456da5 (
  .vcbab45(w2),
  .v0e28cb(w3),
  .v3ca442(w4)
 );
 v053dc2 vdfab80 (
  .vf54559(w0),
  .va4102a(w1),
  .ve8318d(w3)
 );
endmodule

//---------------------------------------------------
//-- Edges-detector
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Edges detector. It generates a 1-period pulse (tic) when either a rising edge or a falling edge is detected on the input
//---------------------------------------------------
//---- Top entity
module vdc93d6 (
 input v717e81,
 input ve7f5e6,
 output v3c12b5
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 assign w0 = ve7f5e6;
 assign v3c12b5 = w2;
 assign w3 = v717e81;
 assign w4 = v717e81;
 assign w4 = w3;
 v053dc2 vbb75a1 (
  .vf54559(w0),
  .ve8318d(w1),
  .va4102a(w4)
 );
 v053dc2 vf6c433 (
  .vf54559(w1),
  .ve8318d(w2),
  .va4102a(w3)
 );
endmodule

//---------------------------------------------------
//-- Sync-x01
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Sync 1-bit input with the system clock domain
//---------------------------------------------------
//---- Top entity
module vad96dc #(
 parameter v6a9fe4 = 0
) (
 input v27dec4,
 output v4642b6
);
 localparam p0 = v6a9fe4;
 wire w1;
 wire w2;
 wire w3;
 assign w2 = v27dec4;
 assign v4642b6 = w3;
 vd12401 v5b01c7 (
  .v0e28cb(w1),
  .v3ca442(w2),
  .vcbab45(w3)
 );
 v6b14d5 #(
  .vc5c8ea(p0)
 ) v94e17e (
  .v268bfc(w1)
 );
endmodule

//---------------------------------------------------
//-- not-wire-x01
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Select positive or negative logic for the input (0=positive, 1=negative)
//---------------------------------------------------
//---- Top entity
module v6b14d5 #(
 parameter vc5c8ea = 0
) (
 output v268bfc
);
 localparam p0 = vc5c8ea;
 wire w1;
 assign v268bfc = w1;
 v6b14d5_v465065 #(
  .VALUE(p0)
 ) v465065 (
  .k(w1)
 );
endmodule

//---------------------------------------------------
//-- 1-bit-gen-constant
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 1-bit generic constant (0/1)
//---------------------------------------------------

module v6b14d5_v465065 #(
 parameter VALUE = 0
) (
 output k
);
 assign k = VALUE;
endmodule
